### ISSUE TITLE
Trying to find various Myenergi values in Node Red

### ISSUE THREAD

**Issue by Mikee1234K** [bisand/myenergi-api#10]
![Myenergi screenshot](https://user-images.githubusercontent.com/72687610/230603750-592c51cc-b47d-4e9e-a2fd-8dc610ae2480.png)
I am using the Node Red Myenergi palette to get data from my Zappie, Eddie and Harvi into Node Red. I have found the values for power going into those in the data coming from the getZappiAll node and the getEddieAll nodes.
I am looking for the following (if it exists)
Is the car connected to the Zappi
How many kWh has Zappi charged in this session (or today)
How many kWh has Harvi diverted today

This is shown on the website, (see screenshot above) so I hope this data is available

Adn how can I set the Minimum green level for the Zappi from Node Red ?

**Comment by biddster** [comment]
I'm not sure about some of your questions, but I submitted a PR here...

https://github.com/brookesdjb/node-red-contrib-myenergi/pull/1

...to addd MGL etc to the node red zappi nodes. Might be worth chasing @brookesdjb to get my PR merged.
