### ISSUE TITLE
Problem when API Servers not available

### ISSUE THREAD

**Issue by Sniks6** [bisand/myenergi-api#4]
Hi there,

I am using this library with the iobroker to get Zappi states into my home homeautmation.
Today my JS Controller hung up / crashed  serveral times because of this error message:

> Too many redirects: director.myenergi.net

or

> Too many redirects: s18.myenergi.net

I think myenergi did maintenance work on their servers and the servers were not available.

Perhaps it would be possible to catch those errors in order to prevent such crashes.
Thank you very much in advance.
 
 Regards, Alex

**Comment by dj-mib** [comment]
Same problem when using this api with iobroker, JS-Controler crahes when myenergi servers are not available.

Best regards
Michael

**Comment by MPTrixi** [comment]
Dito

**Comment by juggi1962** [comment]
Ich habe leider auch dieses Problem.
Wäre echt super wenn man da was machen kann.
Hab 109 Skripte, die dann nicht mehr funktionieren und das ist gar nicht gut.
Danke im Voraus.

**Comment by Sniks6** [comment]
Hi juggi1962,
ich habe genau das gleiche Problem mit dem ioBroker und Javascript Adapter. 
Nachdem bei mir dann auch alle Scripte nicht mehr liefen, habe ich eine zweite Javascript Instanz installiert und nur die Zappi Scripte dort laufen lassen. 
Sollte es mal wieder ein Problem geben, dann stürzt hoffentlich nur diese Instanz ab und die übrigen Scripte laufen weiter.
Vielleicht hilft das weiter.

LG, Alex

**Comment by juggi1962** [comment]
> Hi juggi1962, ich habe genau das gleiche Problem mit dem ioBroker und Javascript Adapter. Nachdem bei mir dann auch alle Scripte nicht mehr liefen, habe ich eine zweite Javascript Instanz installiert und nur die Zappi Scripte dort laufen lassen. Sollte es mal wieder ein Problem geben, dann stürzt hoffentlich nur diese Instanz ab und die übrigen Scripte laufen weiter. Vielleicht hilft das weiter.
> 
> LG, Alex

Vielen Dank für den Tipp, hab es gerade umgesetzt.

**Comment by bisand** [comment]
Sorry for the late reply!
I have now started on a fix to hopefully overcome these errors. I'll post an update when it's ready.
Thanks!

**Comment by bisand** [comment]
A new version is out. I would be happy if you could take it for a spin. The new version should catch all (hopefully) network errors and instead return a default value from the different methods.
I bumped the version to 2.0.0 to reflect the changes and the changed behavior of the methods in the myenergi client.
Please report back if you experience more problems. I will close this issue.
Thanks!
