### ISSUE TITLE
-12 response trying to set boost mode

### ISSUE THREAD

**Issue by biddster** [bisand/myenergi-api#8]
Apologies if I've missed something obvious, but I'm struggling to get boost mode (or charge mode) to work.

Here's the code:

```javascript
require('dotenv').config();

const { MyEnergi, ZappiBoostMode, ZappiChargeMode } = require('myenergi-api');

(async () => {
    const myenergi = new MyEnergi(process.env.HUB_SERIAL, process.env.API_KEY);

    let zappiAll = await myenergi.getStatusZappiAll();
    console.log(zappiAll);

    let result = await myenergi.setZappiBoostMode(
        process.env.HUB_SERIAL,
        ZappiBoostMode.Manual,
        50
    );
    console.log(result);

    // result = await myenergi.setZappiChargeMode(process.env.HUB_SERIAL, ZappiChargeMode.Fast);
    // console.log(result);

    zappiAll = await myenergi.getStatusZappiAll();
    console.log(zappiAll);
})()
    .then(() => process.exit(0))
    .catch((err) => {
        console.error(err);
        process.exit(1);
    });

```

The getStatusZappiAll calls work correctly, however the `result` is always `{ status: '-12', statustext: '' }`

**Comment by bisand** [comment]
I see that you are using process.env.HUB_SERIAL as the Zappi serial. Does that mean that you have a Zappi with a built-in hub? And does that serial number correspond with the serial number you receive from getStatusZappiAll()?

**Comment by biddster** [comment]
Penny drops. Thank you. Zappi serial and hub serial are different things!!!!
